Rh testing
nss-day-cohort-45/nutyshell-talking-to-strangers-1 pull request #20
Opened 2021-01-14 21:45 UTC by Rhowie86

# Description
Basic news component functionality and minimal styling.
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
# Testing Instructions
-fetch the branch and checkout rh-testing
-serve the branch and check out the news form
-fill it out and make sure it is re-rendering the dom with news cards
-make sure that the structure in your database.json looks correct, and new objects are adding correctly
# Checklist:
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [x ] I have added test instructions that prove my fix is effective or that my feature works

2021-01-14 22:03 UTC, cslunetta approved these changes
Looks good!
👍🏻

2021-01-14 22:05 UTC, anna-moore requested changes
Please add comments and your name on top of your files 
(the styling looks really good!!)

2021-01-15 15:44 UTC, christinaashworth commented
👍

2021-01-15 16:16 UTC, anna-moore approved these changes

2021-01-15 16:17 UTC, merged